namespace FreeSR.Proto
{
	using ProtoBuf;
	public enum CHEKDMHGJCL
	{
		ROGUE_MODIFIER_SOURCE_NONE = 0,
		ROGUE_MODIFIER_SOURCE_DICE_ROLL = 1,
		ROGUE_MODIFIER_SOURCE_AEON = 2,
		ROGUE_MODIFIER_SOURCE_BOARD_EVENT = 3,
		ROGUE_MODIFIER_SOURCE_DIALOG_EVENT = 4,
		ROGUE_MODIFIER_SOURCE_MIRACLE = 5,
		ROGUE_MODIFIER_SOURCE_CELL_MARK = 6,
		ROGUE_MODIFIER_SOURCE_AEON_TALENT = 7,
		ROGUE_MODIFIER_SOURCE_BOSS_DECAY = 8,
	}

}
