namespace FreeSR.Proto
{
	using ProtoBuf;
	public enum EBPODFINJNB
	{
		CHESS_ROGUE_MIRACLE_SOURCE_TYPE_NONE = 0,
		CHESS_ROGUE_MIRACLE_SOURCE_TYPE_SELECT = 1,
		CHESS_ROGUE_MIRACLE_SOURCE_TYPE_DIALOGUE = 2,
		CHESS_ROGUE_MIRACLE_SOURCE_TYPE_BONUS = 3,
		CHESS_ROGUE_MIRACLE_SOURCE_TYPE_USE = 4,
		CHESS_ROGUE_MIRACLE_SOURCE_TYPE_RESET = 5,
		CHESS_ROGUE_MIRACLE_SOURCE_TYPE_REPLACE = 6,
		CHESS_ROGUE_MIRACLE_SOURCE_TYPE_TRADE = 7,
		CHESS_ROGUE_MIRACLE_SOURCE_TYPE_GET = 8,
		CHESS_ROGUE_MIRACLE_SOURCE_TYPE_SHOP = 9,
	}

}
