namespace FreeSR.Proto
{
	using ProtoBuf;
	public enum EIIFCEFILPL
	{
		CHESS_ROGUE_BUFF_SOURCE_TYPE_NONE = 0,
		CHESS_ROGUE_BUFF_SOURCE_TYPE_SELECT = 1,
		CHESS_ROGUE_BUFF_SOURCE_TYPE_ENHANCE = 2,
		CHESS_ROGUE_BUFF_SOURCE_TYPE_MIRACLE = 3,
		CHESS_ROGUE_BUFF_SOURCE_TYPE_DIALOGUE = 4,
		CHESS_ROGUE_BUFF_SOURCE_TYPE_BONUS = 5,
		CHESS_ROGUE_BUFF_SOURCE_TYPE_SHOP = 6,
		CHESS_ROGUE_BUFF_SOURCE_TYPE_DICE = 7,
		CHESS_ROGUE_BUFF_SOURCE_TYPE_AEON = 8,
	}

}
