namespace FreeSR.Proto
{
	using ProtoBuf;
	public enum FNMKPDMCOAJ
	{
		ROGUE_BUFF_SOURCE_TYPE_NONE = 0,
		ROGUE_BUFF_SOURCE_TYPE_SELECT = 1,
		ROGUE_BUFF_SOURCE_TYPE_ENHANCE = 2,
		ROGUE_BUFF_SOURCE_TYPE_MIRACLE = 3,
		ROGUE_BUFF_SOURCE_TYPE_DIALOGUE = 4,
		ROGUE_BUFF_SOURCE_TYPE_BONUS = 5,
	}

}
