namespace FreeSR.Proto
{
	using ProtoBuf;
	public enum GameplayCounterUpdateReason
	{
		GAMEPLAY_COUNTER_UPDATE_REASON_NONE = 0,
		GAMEPLAY_COUNTER_UPDATE_REASON_ACTIVATE = 1,
		GAMEPLAY_COUNTER_UPDATE_REASON_DEACTIVATE = 2,
		GAMEPLAY_COUNTER_UPDATE_REASON_CHANGE = 3,
	}

}
