namespace FreeSR.Proto
{
	using ProtoBuf;
	public enum GDNOLKMGDDG
	{
		ROGUE_COMMON_MIRACLE_DISPLAY_TYPE_NONE = 0,
		ROGUE_COMMON_MIRACLE_DISPLAY_TYPE_ADD = 1,
		ROGUE_COMMON_MIRACLE_DISPLAY_TYPE_REMOVE = 2,
		ROGUE_COMMON_MIRACLE_DISPLAY_TYPE_REPAIR = 3,
	}

}
