namespace FreeSR.Proto
{
	using ProtoBuf;
	public enum JCLHFHNFAMA
	{
		CHESS_ROGUE_LEVEL_IDLE = 0,
		CHESS_ROGUE_LEVEL_PROCESSING = 1,
		CHESS_ROGUE_LEVEL_PENDING = 2,
		CHESS_ROGUE_LEVEL_FINISH = 3,
		CHESS_ROGUE_LEVEL_FAILED = 4,
		CHESS_ROGUE_LEVEL_FORCE_FINISH = 5,
	}

}
