namespace FreeSR.Proto
{
	using ProtoBuf;
	public enum NEPLNJIIONC
	{
		CHESS_ROGUE_CELL_SPECIAL_TYPE_NONE = 0,
		CHESS_ROGUE_CELL_SPECIAL_TYPE_LOCKED = 1,
		CHESS_ROGUE_CELL_SPECIAL_TYPE_REPLICATE = 2,
		CHESS_ROGUE_CELL_SPECIAL_TYPE_PROTECTED = 3,
		CHESS_ROGUE_CELL_SPECIAL_TYPE_SEED = 4,
	}

}
