namespace FreeSR.Proto
{
	using ProtoBuf;

	public enum NGCGMKGDCFG
	{
		ROGUE_HANDBOOK_BUFF_STATUS_LOCK = 0,
		ROGUE_HANDBOOK_BUFF_STATUS_UNLOCK = 1,
		ROGUE_HANDBOOK_BUFF_STATUS_MEET = 2,
		ROGUE_HANDBOOK_BUFF_STATUS_GET = 3,
	}
	
}
